version: '3'
services:
  broker:
    build: broker
    ports:
      - "9000:9000"
  auldfellas:
    build: auldfellas
    environment:
      HOSTNAME: auldfellas
#    ports:
#      - "9001:9001"
    depends_on:
      - broker

  dodgydrivers:
    build: dodgydrivers
    environment:
      HOSTNAME: dodgydrivers
#    ports:
#      - "9003:9003"
    depends_on:
      - broker

  girlpower:
    build: girlpower
    environment:
      HOSTNAME: girlpower
#    ports:
#      - "9002:9002"
    depends_on:
      - broker

  client:
    build: client
    environment:
      HOSTNAME: broker
    depends_on:
      - auldfellas
      - dodgydrivers
      - girlpower
      - broker